const { Client } = require('pg');
const password = process.env.PASSWORD;

const SQL = `
    CREATE TABLE IF NOT EXISTS categories(
        id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        name TEXT NOT NULL,
        parent_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
        image_url TEXT,
        position INTEGER GENERATED BY DEFAULT AS IDENTITY
    );

    CREATE TABLE IF NOT EXISTS items(
        id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        name TEXT NOT NULL,
        root_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
        category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
        image_url TEXT,
        description TEXT,
        promote BOOLEAN DEFAULT FALSE
    );

    
`;

async function seed() {
    const client = new Client({
        connectionString: `postgresql://roman:${password}@localhost:5432/inventory_app`
    })

    await client.connect();
    await client.query(SQL);
    await client.end();
}

seed();